### PR TITLE
Bump up mattermost version to v4.5

### PR DESCRIPTION
**Pull request by kaakaa**

### CODE REVIEW

**Comment by kaakaa** [comment]
TODO: 
We should release matterpoll-emoji v0.1.0 before merging this PR.
And we'll release matterpoll-emoji v0.2.0 after merging this PR. v0.2.0 don't support go1.7.

After bumping up mattermost version to 4.5, CI using go1.7 is failed.

```
$ make coverage
go test -coverprofile=coverage.txt -covermode=atomic ./poll/
# github.com/kaakaa/matterpoll-emoji/vendor/github.com/mattermost/mattermost-server/model
vendor/github.com/mattermost/mattermost-server/model/post_list.go:87: undefined: sort.Slice
FAIL	github.com/kaakaa/matterpoll-emoji/poll [build failed]
make: *** [coverage] Error 2
The command "make coverage" exited with 2.
```
